import Foundation
import Darwin

public struct CleanupCandidate: Identifiable, Sendable {
    public let id: NodeID
    public let url: URL
    public let reason: String
    public let allocatedBytes: Int64
    public let logicalBytes: Int64
    public let sizeText: String
}

public struct CleanupFailure: Sendable {
    public let url: URL
    public let message: String
}

public struct CleanupResult: Sendable {
    public var moved: [URL] = []
    public var failures: [CleanupFailure] = []
}

public enum CleanupError: LocalizedError {
    case ineligible, changed
    public var errorDescription: String? {
        switch self {
        case .ineligible: return "This folder is not eligible for development cleanup. Rescan and review the results."
        case .changed: return "This folder or its enclosing path changed since the scan. Rescan before trying again."
        }
    }
}

public enum DevelopmentCleanup {
    private static let excludedNames: Set<String> = [".git", ".Trash", ".Trashes"]
    private static let recognizedNames: Set<String> = ["node_modules", "__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache", ".venv", "venv", ".build", "target", "bin", "obj", ".gradle", ".next", ".nuxt", ".svelte-kit", ".parcel-cache", ".turbo", "dist", "build"]
    private static let protectedPaths = ["/System", "/Library", "/usr", "/bin", "/sbin", "/dev", "/etc", "/private/etc"]

    private static func excludedRoot(_ url: URL) -> Bool {
        let packageExtensions: Set<String> = ["app", "bundle", "framework", "plugin", "photoslibrary", "photolibrary", "musiclibrary", "imovielibrary", "fcpbundle", "band", "logicx", "vmwarevm", "pvm", "sparsebundle"]
        if url.pathComponents.contains(where: {
            excludedNames.contains($0) || $0 == "node_modules" || packageExtensions.contains(($0 as NSString).pathExtension.lowercased())
        }) { return true }
        var ancestor = url
        while ancestor.path != "/" {
            if (try? ancestor.resourceValues(forKeys: [.isPackageKey]))?.isPackage == true { return true }
            ancestor.deleteLastPathComponent()
        }
        return false
    }

    private static func isProtected(_ url: URL) -> Bool {
        protectedPaths.contains { url.path == $0 || url.path.hasPrefix($0 + "/") }
    }

    /// Name-based suggestions, never a guarantee that a folder has no user edits.
    private static func reason(for id: NodeID, in index: ScanIndex) -> String? {
        let node = index[id]
        guard node.kind == .folder, recognizedNames.contains(node.name), let parent = node.parent else { return nil }
        let siblings = Set(index[parent].children.filter { index[$0].kind == .file }.map { index[$0].name })
        switch node.name {
        case "node_modules": return "Installed JavaScript dependencies; restore with your package manager."
        case "__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache": return "Python cache; regenerated by Python or its tools."
        case ".venv", "venv":
            if node.children.contains(where: { index[$0].name == "pyvenv.cfg" && index[$0].kind == .file }) {
                return "Python virtual environment; recreate it and reinstall dependencies."
            }
        case ".build" where siblings.contains("Package.swift"):
            return "Swift package build output and downloaded dependencies; restored by Swift builds."
        case "target":
            if siblings.contains("Cargo.toml") { return "Rust build output; regenerated by Cargo." }
            if siblings.contains("pom.xml") { return "Maven build output; regenerated by Maven." }
        case "bin", "obj":
            if siblings.contains(where: { ["csproj", "fsproj", "vbproj"].contains(($0 as NSString).pathExtension) }) {
                return ".NET build output; regenerated by dotnet build or your IDE."
            }
        case ".gradle":
            if !siblings.isDisjoint(with: ["build.gradle", "build.gradle.kts", "settings.gradle", "settings.gradle.kts"]) {
                return "Project-local Gradle cache; regenerated by Gradle."
            }
        case ".next", ".nuxt", ".svelte-kit", ".parcel-cache", ".turbo":
            guard siblings.contains("package.json") else { return nil }
            return "JavaScript framework output or cache; regenerated by project tools."
        case "dist", "build":
            if siblings.contains("package.json") {
                return "Likely JavaScript build output. Check for hand-written files before removing."
            }
            if node.name == "build", !siblings.isDisjoint(with: ["build.gradle", "build.gradle.kts"]) {
                return "Gradle build output; regenerated by Gradle."
            }
        default: break
        }
        return nil
    }

    /// Outermost folders only: neither sizes nor actions overlap. Never inspect packages for cleanup.
    public static func candidates(in index: ScanIndex) -> [CleanupCandidate] {
        guard let root = index.nodes.first, root.kind == .folder,
              !isProtected(index.rootURL), !excludedRoot(index.rootURL) else { return [] }
        // A dependency/cache folder scanned directly is never a cleanup root or a source of nested suggestions.
        let generatedRoots: Set<String> = ["node_modules", "__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache", ".venv", "venv", ".build", "target", ".next", ".nuxt", ".svelte-kit", ".parcel-cache", ".turbo"]
        guard !generatedRoots.contains(root.name) else { return [] }
        var stack = root.children.reversed().map { $0 }, result: [CleanupCandidate] = []
        while let id = stack.popLast() {
            let node = index[id]
            guard node.kind == .folder, !node.cloud, !excludedNames.contains(node.name) else { continue }
            let url = index.url(for: id)
            guard !isProtected(url) else { continue }
            if let reason = reason(for: id, in: index) {
                if !node.isPartial, node.identity != nil {
                    result.append(CleanupCandidate(id: id, url: url, reason: reason,
                                                   allocatedBytes: node.allocatedBytes, logicalBytes: node.logicalBytes,
                                                   sizeText: node.sizeLabel(.allocated)))
                }
                continue
            }
            stack.append(contentsOf: node.children.reversed())
        }
        return result.sorted { $0.allocatedBytes == $1.allocatedBytes ? $0.url.path < $1.url.path : $0.allocatedBytes > $1.allocatedBytes }
    }

    /// Revalidate every enclosing directory as well as the target immediately before the move.
    public static func validate(_ candidate: CleanupCandidate, in index: ScanIndex) throws {
        guard index.contains(candidate.id), candidate.id != 0,
              index.url(for: candidate.id) == candidate.url,
              reason(for: candidate.id, in: index) != nil,
              !index[candidate.id].isPartial, !isProtected(candidate.url) else { throw CleanupError.ineligible }
        guard index.rootURL.standardizedFileURL.path == index.rootURL.resolvingSymlinksInPath().path else { throw CleanupError.changed }
        for id in index.ancestors(of: candidate.id) {
            let node = index[id], url = index.url(for: id)
            var info = stat()
            guard node.kind == .folder, !node.cloud, !excludedNames.contains(node.name),
                  lstat(url.path, &info) == 0, info.st_mode & S_IFMT == S_IFDIR,
                  FileIdentity(device: Int64(info.st_dev), inode: UInt64(info.st_ino)) == node.identity else { throw CleanupError.changed }
        }
    }

    /// No permanent-delete fallback. The injectable move is used by disposable-fixture checks.
    public static func moveToTrash(ids: Set<NodeID>, in index: ScanIndex,
                                   move: (URL) throws -> Void = { try FileManager.default.trashItem(at: $0, resultingItemURL: nil) }) -> CleanupResult {
        var result = CleanupResult()
        let eligible = candidates(in: index)
        let eligibleIDs = Set(eligible.map(\.id))
        for id in ids.sorted() where !eligibleIDs.contains(id) {
            result.failures.append(CleanupFailure(url: index.contains(id) ? index.url(for: id) : index.rootURL,
                                                 message: CleanupError.ineligible.localizedDescription))
        }
        for candidate in eligible where ids.contains(candidate.id) {
            do {
                try validate(candidate, in: index)
                try move(candidate.url)
                result.moved.append(candidate.url)
            } catch {
                result.failures.append(CleanupFailure(url: candidate.url, message: error.localizedDescription))
            }
        }
        return result
    }
}
